### ISSUE TITLE
環境を決める

### ISSUE THREAD

**Issue by naokinkfj** [TamagoClub/bookmark#1]
なにしますか

**Comment by hori031617** [comment]
サーバーは荒木さんが持っているさくらのサーバーを使わせてもらいましょう！

**Comment by arakiisamu** [comment]
DBはMariaDBがよろしいのではないでしょうか？
https://mariadb.org/

**Comment by hori031617** [comment]
WEBサーバーはnginxを使ってみましょう！
http://nginx.org/en/

**Comment by hori031617** [comment]
レコメンド機能を計算するBATCHはPythonで実装しましょう

**Comment by hori031617** [comment]
WebアプリケーションはScalaを採用

**Comment by hori031617** [comment]
Wikiにまとめました。
https://github.com/TamagoClub/bookmark/wiki/%E9%96%8B%E7%99%BA%E7%92%B0%E5%A2%83
